update release workflows

diff --git a/.github/workflows/create-release.yml b/.github/workflows/create-release.yml
--- a/.github/workflows/create-release.yml
+++ b/.github/workflows/create-release.yml
@@ -152,3 +152,48 @@ jobs:
       - name: Output Release Info
         run: |
           echo "Release created with tag ${{ env.next_tag }}"
+
+      - name: Trigger Release Event
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          # Determine the event type based on whether it's a pre-release or a release or draft
+          if [ "${{ github.event.inputs.is_prerelease }}" = "true" ]; then
+            if [ "${{ github.event.inputs.is_draft }}" = "true" ]; then
+              event_type="draft_prerelease_created"
+            else
+              event_type="prerelease_created"
+            fi
+          else
+            if [ "${{ github.event.inputs.is_draft }}" = "true" ]; then
+              event_type="draft_release_created"
+            else
+              event_type="release_created"
+            fi
+          fi
+
+          echo "Triggering repository_dispatch event: $event_type"
+
+          response=$(curl -s -o response.json -w "%{http_code}" \
+            -X POST \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer $GITHUB_TOKEN" \
+            https://api.github.com/repos/${{ github.repository }}/dispatches \
+            -d @- << EOF
+          {
+            "event_type": "$event_type",
+            "client_payload": {
+              "ref": "${{ github.ref }}"
+            }
+          }
+          EOF
+          )
+
+          if [ "$response" -ne 204 ]; then
+            echo "Failed to dispatch release event. HTTP response code: $response"
+            echo "Response body:"
+            cat response.json
+            exit 1
+          else
+            echo "Release event dispatched successfully!"
+          fi
